import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import FirebaseWrapProvider from '@/_provider/FirebaseWrapProvider'
import Header from '@/_components/Header'
import './globals.scss'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='ja'>
      <body className={inter.className}>
        <FirebaseWrapProvider>
          <Header />
          <main className='container m-2 mx-auto border-2 p-2'>{children}</main>
        </FirebaseWrapProvider>
      </body>
    </html>
  )
}
